pipeline {
    agent {
        docker {
            image 'maven:3.9.2'
            args '-u root'
        }
    }
    
        parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'declarative', description: 'Especifica la rama a compilar (declarative o testng)')
    }
    stages {
        stage('Prepare Workspace') {
            steps {
                script {
                    def workspace = env.WORKSPACE
                    if (fileExists("${workspace}")) {
                        echo "Eliminando workspace existente..."
                        sh "rm -rf ${workspace}/* ${workspace}/.* || true"           
                    }
                }
            }
        }
         
        
       stage('Checkout') {
            steps {
                echo "Clonando la rama seleccionada: ${BRANCH_NAME}"
                git branch: "${BRANCH_NAME}", url: 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }


        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }
}
